Repository Biomed-uz/BioMed, pull requests merged in 2024-01, with the labels that each got.

#45 Created EntityNotFoundException exception class
  BioMed.Api/BioMed.Domain/Exceptions/EntityNotFoundException.cs
Labels: Task

#47 Create Librery Infrastructure
  BioMed.Api/Bio.Med.Infrastructure/BioMed.Infrastructure.csproj
  BioMed.Api/Bio.Med.Infrastructure/Class1.cs
  BioMed.Api/BioMed.Api.sln
Labels: Task

#48 Create DTOs
  BioMed.Api/BioMed.Domain/DTOs/AnalysisType/AnalysisTypeDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/AnalysisType/AnalysisTypeForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/AnalysisType/AnalysisTypeForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Department/DepartmentDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Department/DepartmentForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Department/DepartmentForupdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Disease/DiseaseDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Disease/DiseaseForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Disease/DiseaseForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/DiseaseCategory/DiseaseCategoryDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/DiseaseCategory/DiseaseCategoryForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/DiseaseCategory/DiseaseCategoryForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Doctor/DoctorDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Doctor/DoctorForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Doctor/DoctorForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/LaboratoryResult/LaboratoryResultDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/LaboratoryResult/LaboratoryResultForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/LaboratoryResult/LaboratoryResultForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Patient/PatientDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Patient/PatientForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Patient/PatientForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Payment/PaymentDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Payment/PaymentForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Payment/PaymentForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Spesialization/SpesializationDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Spesialization/SpesializationForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Spesialization/SpesializationForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Treatment/TreatmentDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Treatment/TreatmentForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Treatment/TreatmentForUpdateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Visit/VisitDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Visit/VisitForCreateDTO.cs
  BioMed.Api/BioMed.Domain/DTOs/Visit/VisitForUpdateDTO.cs
Labels: Task

#52 25 download necessary nuget packages
  BioMed.Api/BioMed.Api.sln
  BioMed.Api/BioMed.Api/BioMed.Api.csproj
  BioMed.Api/BioMed.Domain/BioMed.Domain.csproj
Labels: enhancement

#55 Update BioMed.Infrastructura library
  BioMed.Api/Bio.Med.Infrastructure/BioMed.Infrastructure.csproj
Labels: Task

#49 Created ResourceParameters for all Entities
  BioMed.Api/BioMed.Domain/ResourceParameters/AnalysisTypeResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/DepartmentResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/DiseaseCategoryResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/DiseaseResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/DoctorResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/LaboratoryResultResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/PatientResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/PaymentResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/ResourceParametersBase.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/SpesializationResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/TreatmentResourceParameters.cs
  BioMed.Api/BioMed.Domain/ResourceParameters/VisitResourceParameters.cs
Labels: Task, enhancement

#62 Create Repositories
  BioMed.Api/BioMed.Domain/Interfaces/Repositories/ICommonRepository.cs
  BioMed.Api/BioMed.Domain/Interfaces/Repositories/IVisitRepostory.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/AnalysisTypeRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/DepartmentRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/DiseaseCategoryRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/DiseaseRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/DoctorRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/LaboratoryResultRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/PatientRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/PaymentRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/RepositoryBase.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/SpesializationRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/TreatmentRepository.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Repositories/VisitRepository.cs
Labels: Task

#61 Create Configuration
  BioMed.Api/BioMed.Domain/Entities/Disease.cs
  BioMed.Api/BioMed.Domain/Entities/Spesialization.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/AnalysisTypeEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/DepartmentEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/DiseaseCategoryEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/DiseaseEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/DoctorEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/LaboratoryResultEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/PatientEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/PaymentEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/SpesializationEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/TreatmentEntityConfiguration.cs
  BioMed.Api/BioMed.Infrastructure/Persistence/Configuration/VisitEntityConfiguration.cs
Labels: Task

#64 Created ConfigureServicesExtensions
  BioMed.Api/BioMed.Api/BioMed.Api.csproj
  BioMed.Api/BioMed.Api/Extensions/ConfigureServicesExtensions.cs
Labels: Task

#65 Create ErrorHandlerMiddleware class
  BioMed.Api/BioMed.Api/Middlewares/ErrorHandlerMiddleware.cs
  BioMed.Api/BioMed.Api/Program.cs
Labels: Task

#67 create spesialization service
  BioMed.Api/BioMed.Api.sln
  BioMed.Api/BioMed.Infrastructure/BioMed.Infrastructure.csproj
  BioMed.Api/BioMed.Services/BioMed.Services.csproj
  BioMed.Api/BioMed.Services/Class1.cs
  BioMed.Api/BioMed.Services/Services/SpesializationService.cs
Labels: Task, enhancement

#70 31 create department service
  BioMed.Api/BioMed.Services/Services/DepartmentService.cs
  BioMed.Api/BioMed.Services/Services/SpesializationService.cs
Labels: Task

#77 Create DiseaseCategoryService class
  BioMed.Api/BioMed.Domain/Interfaces/Services/IDiseaseCategoryService.cs
  BioMed.Api/BioMed.Services/Services/DiseaseCategoryService.cs
Labels: Task

#76 Create DiseaseService
  BioMed.Api/BioMed.Services/Services/DiseaseService.cs
Labels: Task

#75 Create VisitService class
  BioMed.Api/BioMed.Services/Services/VisitService.cs
Labels: Task

#74 Create TreatmentService class
  BioMed.Api/BioMed.Services/Services/TreatmentService.cs
Labels: Task

#73 Create PaymentService class
  BioMed.Api/BioMed.Services/Services/PaymentService.cs
Labels: Task

#72 Create PatientService class
  BioMed.Api/BioMed.Services/Services/PatientService.cs
Labels: Task

#71 34 create doctor service
  BioMed.Api/BioMed.Domain/ResourceParameters/DoctorResourceParameters.cs
  BioMed.Api/BioMed.Services/Services/DoctorService.cs
Labels: Task

#78 Create LaboratoryResultService class
  BioMed.Api/BioMed.Services/Services/DiseaseService.cs
  BioMed.Api/BioMed.Services/Services/LaboratoryResultService.cs
  BioMed.Api/BioMed.Services/Services/PatientService.cs
Labels: Task

#79 Create AnalysisTypeService class
  BioMed.Api/BioMed.Services/Services/AnalysisTypeService.cs
Labels: Task

#80 Create Controllers
  BioMed.Api/BioMed.Api/BioMed.Api.csproj
  BioMed.Api/BioMed.Api/Controllers/AnalysisTypeController.cs
  BioMed.Api/BioMed.Api/Controllers/DepartmentController.cs
  BioMed.Api/BioMed.Api/Controllers/DiseaseCategoryController.cs
  BioMed.Api/BioMed.Api/Controllers/DiseaseController.cs
  BioMed.Api/BioMed.Api/Controllers/DoctorController.cs
  BioMed.Api/BioMed.Api/Controllers/LaboratoryResultController.cs
  BioMed.Api/BioMed.Api/Controllers/PatientController.cs
  BioMed.Api/BioMed.Api/Controllers/PaymentController.cs
  BioMed.Api/BioMed.Api/Controllers/SpesializationController.cs
  BioMed.Api/BioMed.Api/Controllers/TreatmentController.cs
  BioMed.Api/BioMed.Api/Controllers/VisitController.cs
  BioMed.Api/BioMed.Domain/Pagination/PagenationMetaData.cs
Labels: Task

#82 Create Authentication
  BioMed.Api/BioMed.Api/BioMed.Api.csproj
  BioMed.Api/BioMed.Api/Controllers/AuthentocationController.cs
  BioMed.Api/BioMed.Api/LoginModels/LoginRequest.cs
  BioMed.Api/BioMed.Api/LoginModels/User.cs
  BioMed.Api/BioMed.Api/Program.cs
Labels: Task
